[package]
name = "heron_debug"
version = "0.1.0-dev"
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "Rendering of Heron's collision shapes for debugging purposes"
repository = "https://github.com/jcornaz/heron/"

[features]
default = []
2d = ["bevy_prototype_lyon"]
3d = []

[dependencies]
heron_core = { path = "../core", version = "^0.1.0-dev"}
bevy_math = { git = "https://github.com/bevyengine/bevy.git" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git" }
bevy_render = { git = "https://github.com/bevyengine/bevy.git" }
bevy_sprite = { git = "https://github.com/bevyengine/bevy.git" }
bevy_asset = { git = "https://github.com/bevyengine/bevy.git" }
bevy_prototype_lyon = { git = "https://github.com/Nilirad/bevy_prototype_lyon.git", branch = "master", optional = true }
fnv = "^1.0"
